# config file saving all important data
%YAML 1.1
---
- dataworks:
    folders:
          urs:
            wdir:     '/home/urs/sync/projects/autostim'
            patlist:  '/home/urs/sync/projects/autostim/data/patientenliste_onoff.xlsx'
            datpath:  '/home/urs/sync/projects/autostim/data/csvdata/nopca/'
          david:
            wdir:     '/media/storage/iPScnn'
            patlist:  '/media/david/windows/Dokumente und Einstellungen/dpedr/Jottacloud/onoff_svm/patientenliste_onoff.xlsx'
            datpath:  '/media/david/windows/Dokumente und Einstellungen/dpedr/Jottacloud/onoff_svm/analyses/csvdata/nopca/'
    ignbad: true
    scaling: true
    conds: ['ON', 'OFF']
    tasks:
      - 'hld'
      - 'dd'
      - 'tap'
    dev:
      - 'ACC'
      - 'GYRO'


